---
title: "Data Visualization"
output: html_document
date: "2025-04-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Visualization

```{r}
library(tidyverse)
library(palmerpenguins)
library(ggthemes)
```

```{r}
penguins
```

```{r}
glimpse(penguins)
```

```{r}
levels(penguins$island)
```

```{r}
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g, color = species)
) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(mapping = aes(color = species, shape = species)) +
  geom_smooth(method = "lm")
```

```{r}
ggplot(penguins, 
       aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species, shape = species)) +
  geom_smooth(method = "lm") +
  labs(
    title = "Body mass and flipper length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper length (mm)", y = "Body mass (g)",
    color = "Species", shape = "Species"
  ) +
  scale_color_colorblind()
```

## Distributions

### Categorical

#### Bar

```{r}
ggplot(penguins, aes(x = species)) +
  geom_bar()
```

> Reorder based on frequency

```{r}
ggplot(penguins, aes(x = fct_infreq(species))) +
  geom_bar()
```

### Numeric

#### Histogram

```{r}
ggplot(penguins, aes(x = body_mass_g)) +
  geom_histogram(binwidth = 200)
```

#### Density

```{r}
ggplot(penguins, aes(x = body_mass_g)) +
  geom_density()
```

## Relationships

### Numerical and Categorical

#### Boxplot

```{r}
ggplot(penguins, aes(x = species, y = body_mass_g)) +
  geom_boxplot()
```

#### Density

```{r}
ggplot(penguins, aes(x = body_mass_g, 
                     color = species, 
                     fill = species)) +
  geom_density(linewidth = 0.75, alpha = 0.5)
```

### Two categorical

#### Bar

```{r}
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar()
```

```{r}
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(position = "fill")
```

### Two numerical

#### Scatter

```{r}
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point()
```

### Three or more

#### Scatter

```{r}
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species, shape = island))
```

#### Facet wrap

```{r}
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species, shape = species)) +
  facet_wrap(~island)
ggsave("images/penguin-plot.png")
```
